name: Release crates.io
on: 
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest    
    environment: cratesio
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dry Run
        run: cargo publish --dry-run
      - name: Publish Release
        run: cargo publish --token ${{secrets.CRATES_IO_SECRET}}
